== Overview
This section contains guidance for the implementation of Prisma Cloud Compute (Twistlock) within public-sector organizations.
Please check up on this site as guidance may change over time.

== Updates
20201012 - Initial release of this guidance.

== Defense Information Systems Agency (DISA) Security Technical Implementation Guides (STIGs)

Prisma Cloud Compute has been assessed to the following STIGs:

- The Console and Defender components of every Prisma Cloud Compute release are assessed against the https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-stig.html[DISA STIG for Red Hat Enterprise Linux 7, xccdf_org.ssgproject.content_profile_stig].
The findings' justifications can be found link:STIG\ssgproject[here].

- Prisma Cloud Compute has been assessed to the https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_ASD_V4R11_STIG.zip[Application Security and Development Security Technical Implementation Guide Version 4, Release: 11 Benchmark Date: 24 Jul 2020].
The findings based upon the vulnerability severity category codes can be found link:STIG/ADS_v4_r11/ASD_v4_r11_overview.adoc[here].


== Federal Risk and Authorization Management Program (FedRAMP)

https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-admin/welcome/pcee_vs_pcce.html[Prisma Cloud Enterprise Edition] is in process for https://marketplace.fedramp.gov/#!/products?sort=productName&productNameSearch=Palo%20Alto%20Networks[FedRAMP Moderate certification].
The Prisma Cloud Compute module is not within the boundaries of this certification and is not available within the FedRAMPed Prisma Cloud Console.
Customers requiring FedRAMP certification should use the self-hosted version, https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/welcome/pcee_vs_pcce.html[Prisma Cloud Compute Edition].
For customers offering their own FedRAMP services that use Prisma Cloud Compute to facilitate in their service's FedRAMP certification,
GSA has drafted guidance for the https://www.fedramp.gov/assets/resources/documents/DRAFT_FedRAMP_Vulnerbility_Scanning_Requirements_for_the_Development_and_Use_of_Containers.pdf[FedRAMP Vulnerability Scanning Requirements for the Deployment and use of Containers].

The configuration settings for Prisma Cloud Compute's features and functions to support an organization's FedRAMP certification can be found link:FedRAMP/fedramp.adoc[here].
